### PR TITLE
Fix #124

### LINKED ISSUE #124: getCurrentPackage returns to wrong label
1. release v1
2. sync and restart
3. release v2
4. sync but don't restart
5. release v3
6. sync but don't restart
7. getCurrentPackage returns: v2 should be v1 because v2 was not installed

### PR DESCRIPTION
**Pull request by geof90**
This PR fixes #124 by ensuring that we only backup the current package if it is not still pending.
Added test coverage for this scenario.

### CODE REVIEW

File: www/localPackage.ts [hunk 1]
```diff
@@ -107,8 +107,19 @@ class LocalPackage extends Package implements ILocalPackage {
     }
 
     private finishInstall(deployDir: DirectoryEntry, installOptions: InstallOptions, installSuccess: SuccessCallback<InstallMode>, installError: ErrorCallback): void {
+        function backupPackageInformationFileIfNeeded(backupIfNeededDone: Callback<void>) {
+            NativeAppInfo.isPendingUpdate((pendingUpdate: boolean) => {
+                if (pendingUpdate) {
+                    // Don't back up the  currently installed update since it hasn't been "confirmed"
+                    backupIfNeededDone(null, null);
```
Comment (ryuyu) [inline www/localPackage.ts]: The callback backupIfNeededDone seems to only take one argument. Why are you passing 2 nulls here?

**Comment by ryuyu** [comment]
LGTM

File: www/localPackage.ts (hunk 1 above)
Comment (geof90) [inline www/localPackage.ts]: Cuz TypeScript :(

**Comment by lostintangent** [comment]
LGTM!
